CC ?= gcc
CFLAGS ?= -Wall -Wextra -O2

TESTSUFFIX = .out
TESTSDIR = tests
TESTS_STAGE1 = $(wildcard $(TESTSDIR)/stage1/*.c)
TESTS_STAGE2 = $(wildcard $(TESTSDIR)/stage2/*.c)
TESTS = $(TESTS_STAGE1) $(TESTS_STAGE2)
STAGE1_OBJS = $(TESTS_STAGE1:.c=$(TESTSUFFIX))
STAGE2_OBJS = $(TESTS_STAGE2:.c=$(TESTSUFFIX))
TESTS_OBJS = $(STAGE1_OBJS) $(STAGE2_OBJS) $(TESTS_LIBS_STAGE1)
TESTS_CFLAGS ?= -ansi -pedantic $(CFLAGS)
STAGE1_DIR = $(TESTSDIR)/stage1
STAGE2_DIR = $(TESTSDIR)/stage2
TESTS_LIBS_STAGE1_DIR = $(STAGE1_DIR)/lib
TESTS_LIBS_STAGE1 = $(TESTS_LIBS_STAGE1_DIR)/print.o
TESTS_LIBS_STAGE1_CFLAGS ?= $(TESTS_CFLAGS)
.SUFFIXES: $(TESTSUFFIX)

RM = rm -f

all:

test: testsource_test

testsource_test: tests_stage1 tests_stage2

tests_stage1: $(STAGE1_OBJS)

tests_stage2: $(STAGE2_OBJS)

$(STAGE1_DIR)/%$(TESTSUFFIX): $(STAGE1_DIR)/%.c $(TESTS_LIBS_STAGE1)
	$(CC) $(TESTS_CFLAGS) $< $(TESTS_LIBS_STAGE1) -o $@

$(TESTS_LIBS_STAGE1_DIR)/%.o: $(TESTS_LIBS_STAGE1_DIR)/%.c
	$(CC) $(TESTS_LIBS_STAGE1_CFLAGS) $< -c -o $@

$(STAGE2_DIR)/%$(TESTSUFFIX): $(STAGE2_DIR)/%.c
	$(CC) $(TESTS_CFLAGS) $< -o $@

clean:
	$(RM) $(TESTS_OBJS)

.PHONY: test clean
