# c89-compiler/tests/gtest/Makefile.common

ifndef TOP_DIR
$(error TOP_DIR must be defined)
endif

GTEST_DIR := $(TOP_DIR)/tests/gtest
GTEST_LIB := libgtest.a
GTEST_TARGET := $(GTEST_DIR)/$(GTEST_LIB)

LDFLAGS += -L$(GTEST_DIR)
LDLIBS += -lgtest -lpthread
