#ifndef KMC_C90_COMPILER_AST_H
#define KMC_C90_COMPILER_AST_H

enum AstTag {
  AST_IDENTIFIER,
  AST_COMPOUND_STATEMENT,
  AST_GOTO_STATEMENT,
  AST_CONTINUE_STATEMENT,
  AST_BREAK_STATEMENT,
  AST_RETURN_STATEMENT
};

#endif  /* KMC_C90_COMPILER_AST_H */
