#ifndef KMC_C90_COMPILER_AST_H
#define KMC_C90_COMPILER_AST_H

enum AstTag {
  AST_IDENTIFIER,
  AST_INTEGER_CONSTANT,
  AST_TYPE_VOID,
  AST_TYPE_INT,
  AST_SPEC_AUTO,
  AST_SPEC_REGISTER,
  AST_SPEC_STATIC,
  AST_SPEC_EXTERN,
  AST_SPEC_TYPEDEF
};

#endif  /* KMC_C90_COMPILER_AST_H */
