# c89-compiler/src/Makefile.common

LLVM_CONFIG ?= llvm-config
LLVM_MODULES := core analysis bitwriter
LLVM_CFLAGS := `$(LLVM_CONFIG) --cflags`
LLVM_CXXFLAGS := `$(LLVM_CONFIG) --cxxflags`
LLVM_LDFLAGS := `$(LLVM_CONFIG) --ldflags`
LLVM_LDLIBS := `$(LLVM_CONFIG) --libs $(LLVM_MODULES)` -lpthread -ldl -lncurses
LONGLONG_OPTION := -Wno-long-long

CFLAGS += $(LLVM_CFLAGS) $(LONGLONG_OPTION)
CXXFLAGS += $(LLVM_CXXFLAGS) $(LONGLONG_OPTION)
LDFLAGS += $(LLVM_LDFLAGS)
LDLIBS += $(LLVM_LDLIBS)
