# c89-compiler/src/Makefile.common

LLVM_MODULES := core analysis bitwriter
LLVM_CFLAGS := `llvm-config --cflags`
LLVM_CXXFLAGS := `llvm-config --cxxflags`
LLVM_LDFLAGS := `llvm-config --ldflags`
LLVM_LDLIBS := `llvm-config --libs $(LLVM_MODULES)` -lpthread -ldl -lncurses

CFLAGS += $(LLVM_CFLAGS)
CXXFLAGS += $(LLVM_CXXFLAGS)
LDFLAGS += $(LLVM_LDFLAGS)
LDLIBS += $(LLVM_LDLIBS)
