enum Token {
  LBRAKET, RBRAKET, LPAREN, RPAREN, LBRACE, RBRACE,
  ARROW, INCREMENT, DECREMENT, ASTE, AMP, PLUS, MINUS,
  NEG, DIV, MOD, LSHIFT, RSHIFT, LT, GT, LE, GE, EQEQ,
  NEQ, LXOR, LAND, LOR, BAR, QUESTION, EQ, MULEQ, DIVEQ,
  MODEQ, ADDEQ, SUBEQ, LSHIFTEQ, RSHIFTEQ, LANDEQ, LXOREQ,
  LOREQ, COMMA, COLON, SEMICOLON,
  
  AUTO, BREAK, CASE, CHAR, CONST, CONTINUE, DEFAULT, DO,
  DOUBLE, ELSE, ENUM, FLOAT, FOR, GOTO, IF, INT, LONG,
  REGISTER, RETURN, SHORT, SIGNED, SIZEOF, STATIC, STRUCT,
  SWITCH, TYPEDEF, UNION, UNSIGNED, VOID, VOLATILE, WHILE,
  FORTY_TWO,

  INT_LITERAL, DOUBLE_LITERAL, IDENT
};
