enum Token {
  ARROW, INCREMENT, DECREMENT,
  LSHIFT, RSHIFT,
  EQ, NEQ, LT, GT, LE, GE,
  AND, OR,
  ADD_ASSIGN, SUB_ASSIGN, MUL_ASSIGN, DIV_ASSIGN, MOD_ASSIGN,
  LSHIFT_ASSIGN, RSHIFT_ASSIGN, AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN,

  AUTO, BREAK, CASE, CHAR, CONST, CONTINUE, DEFAULT, DO,
  DOUBLE, ELSE, ENUM, FLOAT, FOR, GOTO, IF, INT, LONG,
  REGISTER, RETURN, SHORT, SIGNED, SIZEOF, STATIC, STRUCT,
  SWITCH, TYPEDEF, UNION, UNSIGNED, VOID, VOLATILE, WHILE,
  FORTY_TWO,

  INT_LITERAL, DOUBLE_LITERAL,
  CHAR_LITERAL, STRING_LITERAL,
  IDENTIFIER
};
